name: Deploy dbt docs (Data Catalog) to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies and prepare profiles
        run: |
          uv sync --locked
          uv run dbt deps
          cp profiles.cicd.yml profiles.yml

      #- name: âœ… Run linter
      #  run: uv run sqlfluff lint

      - name: ğŸ—ï¸ï¸ Build production environment
        run: uv run dbt build --target prod

      - name: ğŸ—ƒï¸ï¸ Generate Data Catalog
        run: |
          uv run dbt docs generate --target prod
          mkdir docs
          cp target/index.html docs/
          cp target/manifest.json docs/
          cp target/catalog.json docs/

      - name: â¬†ï¸ Commit Data Catalog for GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs